trigger:
  branches:
    include:
      - development  # Ensure this branch triggers the pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
  continueOnError: true   # Allows the pipeline to continue even if errors occur, so you can see more output for debugging
