trigger:
  branches:
    include:
      - development  # This section specifies that the pipeline will be triggered whenever there are changes made to the 'development' branch. Ensure that you push to this branch to activate the pipeline.

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover
  displayName: 'Run Unit Tests'